### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by hopewise** [neomerx/cors-illuminate#11]
I tried to use the package in lumen as:

\bootstrap\app.php

```
$app->routeMiddleware([
    'cors' => \Neomerx\CorsIlluminate\CorsMiddleware::class,
]);
```

in `config/cors-illuminate.php` :

```
Settings::KEY_SERVER_ORIGIN => [
        'scheme' => 'http',
        'host'   => '192.168.99.100',
        'port'   => 9900,
    ],

    /**
     * A list of allowed request origins (lower-cased, no trail slashes).
     * Value `true` enables and value `null` disables origin.
     * If value is not on the list it is considered as not allowed.
     * Environment variables could be used for enabling/disabling certain hosts.
     */
    Settings::KEY_ALLOWED_ORIGINS => [
        'http://192.168.99.100:9900'         => true,
    ],
```

But I got error if I visit the route at the same host of the app:

`Class path.config does not exist`

So, what I am missing?

**Comment by neomerx** [comment]
Installation instruction asks to add provider to `config/app.php`. This approach was tested on Lumen 5.1

However it seems in Lumen 5.2 Taylor changed how applications are configured. I'll take a look on 5.2

**Comment by hopewise** [comment]
OK, I hope it's easy to fix, this emphasize how important it is to do the unit-test homework for my project!

**Comment by neomerx** [comment]
I haven't figured out how Lumen 5.2 uses config files (apart from .env). Nothing seems to be in official documentation and release notes. I've also studied the 5.2 code sources.

The only idea how it should work by 5.2 philosophy is having optional parameter in .env like

```
CORS_ILLUMINATE_CONFIG_PATH=...
```

what are your thoughts on that?

**Comment by hopewise** [comment]
I have no idea, but due to the lack of time, I have tried this repo
https://github.com/barryvdh/laravel-cors, and it worked well with Lumen
5.2, thanks

On Wed, Mar 16, 2016 at 3:26 PM, neomerx notifications@github.com wrote:

> I haven't figured out how Lumen 5.2 uses config files (apart from .env).
> Nothing seems to be in official documentation and release notes. I've also
> studied the 5.2 code sources.
> 
> The only idea how it should work by 5.2 philosophy is having optional
> parameter in .env like
> 
> CORS_ILLUMINATE_CONFIG_PATH=...
> 
> what are your thoughts on that?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/neomerx/cors-illuminate/issues/11#issuecomment-197328345

## 

## 

## Kind Regards,

Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East

**Comment by neomerx** [comment]
@hopewise I created this repo because Barry uses repo which do not follow the CORS spec. And it has some [issues](https://github.com/barryvdh/laravel-cors/issues).

The reason you have the error is because you use Laravel service provider in Lumen app (instead of `\Neomerx\CorsIlluminate\Providers\LumenServiceProvider`). But it might be due to lack of time. If you tried provider for Lumen it would work. However I'll update the documentation anyway.

**Comment by hopewise** [comment]
Ok, I gave it another try, `Class path.config does not exist` is no longer appear, however, I still can't call apis successfully, I get this error:

`XMLHttpRequest cannot load http://192.168.99.100:9907/territory/check_in?token=eyJ0eXAiOiJKV1QiLCJhbGc…FicmkiLCJleHAiOjE0NTgyMDM4NTl9.MOIUGBoj7VsgzUTRzIHfV1xILO2I1rRFWw4GHI2qlI4. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://docker_machine:9900' is therefore not allowed access. The response had HTTP status code 400.`

I thought my settings are correct, can you please check here:

```
//My lumen server is at 192.168.99.100:9907

Settings::KEY_SERVER_ORIGIN => [
        'scheme' => 'http',
        'host'   => '192.168.99.100',
        'port'   => 9907,
    ],
```

And calling origin:

```
 Settings::KEY_ALLOWED_ORIGINS => [
        'http://localhost'         => true,
        'http://docker_machine:9900'         => true,
        'http://some.disabled.com' => null,
    ],

    Settings::KEY_ALLOWED_HEADERS => [
        'content-type'            => null,
        'x-custom-request-header' => null,
    ],

I also tried:

Settings::KEY_ALLOWED_HEADERS => ['*'],


Settings::KEY_EXPOSED_HEADERS => [
        'content-type'             => null,
        'x-custom-response-header' => null,
    ],

I also tried: 
Settings::KEY_EXPOSED_HEADERS => ['*'],

```

And I call it like this:

```
        $('#check_in').click(function(){
            var token= "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiU2FtaXIgU2FicmkiLCJleHAiOjE0NTgyMDM4NTl9.MOIUGBoj7VsgzUTRzIHfV1xILO2I1rRFWw4GHI2qlI4";
            $.ajax({
                url: 'http://192.168.99.100:9907/territory/check_in?token='+token,

                method: "get",
                headers: {
                },
                data: {},
                success: function(data){
                    alert(data);
                }
            });
        });
```

As for Barry repo, my settings that has worked was like this:

```
    'supportsCredentials' => false,
    'allowedOrigins' => ['http://192.168.99.100:9900', 'http://docker_machine:9900'],
    'allowedHeaders' => ['*'],
    'allowedMethods' => ['*'],
    'exposedHeaders' => [],
    'maxAge' => 0,
    'hosts' => [],
```

I have set the useful logging feature, here is my log:

```
[2016-03-17 07:33:36] lumen.DEBUG: CORS analysis for request started.  
[2016-03-17 07:33:36] lumen.DEBUG: Request is identified as a pre-flight CORS request.  
[2016-03-17 07:33:36] lumen.INFO: Request header is not allowed {"header":"accept"} 
[2016-03-17 07:33:36] lumen.DEBUG: CORS analysis for request completed.  
```

Do you any suggestions? thanks..

**Comment by neomerx** [comment]
Your request sends `Accept` header in request. You need to enable this header in

``` php
    Settings::KEY_ALLOWED_HEADERS => [
        ...
        'accept' => true,
    ],
```

make sure it's **lower-cased** as above

Logs should be self-explain (I hope so). If you feel messages could be improved for regular users please let me know.

**Comment by hopewise** [comment]
I did:

```
Settings::KEY_ALLOWED_HEADERS => [
        ...
        'accept' => true,
    ],
```

I got another error:

```
[2016-03-17 13:38:12] lumen.DEBUG: CORS analysis for request started.  
[2016-03-17 13:38:12] lumen.DEBUG: Request is identified as a pre-flight CORS request.  
[2016-03-17 13:38:12] lumen.INFO: Request header is not allowed {"header":"x-csrf-token"} 
[2016-03-17 13:38:12] lumen.DEBUG: CORS analysis for request completed.  
```

But, then I fixed it by my self:

```
Settings::KEY_ALLOWED_HEADERS => [
        ...
        'accept' => true,
        'x-csrf-token' => true,
    ],
```

As for error message, it would be great to add a hint, like, 'accept' => true, and the related settings for the error: KEY_ALLOWED_HEADERS

**Comment by neomerx** [comment]
The package supports storing settings in various places such as databases. Out of the box 'file settings' is just one of them. Thus specifying particular config keys would be incorrect and messages would be

```
[2016-03-17 13:38:12] lumen.INFO: Request header is not allowed. Check config settings for Allowed Headers. {"header":"x-csrf-token"} 
```

I've also added support for allowing all headers.
You will see update today.

**Comment by hopewise** [comment]
Thanks!

**Comment by neomerx** [comment]
update released
