### ISSUE TITLE
Origin as 'file://'. Support for multiple origins in config?

### ISSUE THREAD

**Issue by chimit** [neomerx/cors-illuminate#14]
Hello!
Please, can anybody give an idea, what's wrong. I use Lumen on http://lumen.app URL on my local machine and get this error:

```
[2016-03-18 10:09:54] lumen.ERROR: exception 'InvalidArgumentException' with message 'url' in /home/vagrant/Code/lumen/vendor/neomerx/cors-psr7/src/Http/ParsedUrl.php:70
Stack trace:
#0 /home/vagrant/Code/lumen/vendor/neomerx/cors-psr7/src/Factory/Factory.php(51): Neomerx\Cors\Http\ParsedUrl->__construct('file://')
#1 /home/vagrant/Code/lumen/vendor/neomerx/cors-psr7/src/Analyzer.php(363): Neomerx\Cors\Factory\Factory->createParsedUrl('file://')
#2 /home/vagrant/Code/lumen/vendor/neomerx/cors-psr7/src/Analyzer.php(144): Neomerx\Cors\Analyzer->getOrigin(Object(Neomerx\CorsIlluminate\Adapters\IlluminateRequestToPsr7))
#3 /home/vagrant/Code/lumen/vendor/neomerx/cors-psr7/src/Analyzer.php(114): Neomerx\Cors\Analyzer->analyzeImplementation(Object(Neomerx\CorsIlluminate\Adapters\IlluminateRequestToPsr7))
#4 /home/vagrant/Code/lumen/vendor/neomerx/cors-illuminate/src/CorsMiddleware.php(116): Neomerx\Cors\Analyzer->analyze(Object(Neomerx\CorsIlluminate\Adapters\IlluminateRequestToPsr7))
#5 /home/vagrant/Code/lumen/vendor/neomerx/cors-illuminate/src/CorsMiddleware.php(63): Neomerx\CorsIlluminate\CorsMiddleware->getCorsAnalysis(Object(Illuminate\Http\Request))
#6 [internal function]: Neomerx\CorsIlluminate\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 /home/vagrant/Code/lumen/vendor/illuminate/pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#8 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 /home/vagrant/Code/lumen/vendor/illuminate/pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 /home/vagrant/Code/lumen/vendor/laravel/lumen-framework/src/Application.php(1439): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#11 /home/vagrant/Code/lumen/vendor/laravel/lumen-framework/src/Application.php(1213): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#12 /home/vagrant/Code/lumen/vendor/laravel/lumen-framework/src/Application.php(1153): Laravel\Lumen\Application->dispatch(NULL)
#13 /home/vagrant/Code/lumen/public/index.php(28): Laravel\Lumen\Application->run()
#14 {main}
```

It appears only on POST requests (in Postman).

My config file has:

```
S::KEY_SERVER_ORIGIN => [
        'scheme' => 'http',
        'host'   => 'lumen.app',
        'port'   => 8080
    ],
```

I'm not sure it's correct, but I can't find more documentation for this package. So I don't fully understand why should I specify this parameter.

By the way, how can I specify several hosts in the config file? For production server, for example? Can it automatically detect current origin?

**Comment by neomerx** [comment]
Header `Origin` of your request has value `file://`
It seems the request is not send from page served by server but just an ordinary file. A correct value must be OK for [parse_url](http://php.net/manual/en/function.parse-url.php).
You need to send requests from files served by web server.

**Comment by neomerx** [comment]
Though error handling could be improved for this scenario

**Comment by neomerx** [comment]
I've released a [new version](https://github.com/neomerx/cors-psr7/releases/tag/v1.0.4) which writes to logs that such URLs cannot be parsed. You should

```
$ composer update
```

I'm closing the issue. If you feel it still exists please let me know.

**Comment by pavoltanuska** [comment]
Just ran into this and voila, here's the fix.

Thanks and keep up the good work! :)

**Comment by neomerx** [comment]
@pavoltanuska thanks for your support :star:

**Comment by chimit** [comment]
Thank you the fix! I will try to it!

And what about several servers in S::KEY_SERVER_ORIGIN?

**Comment by neomerx** [comment]
@Chimit If more people do need multiple origins for purpose I will look closer if it's OK with spec and common practices.

**Comment by chimit** [comment]
Sorry, may be I'm wrong, but is it not a common practice to use dev and production environments with different URLs? How can I solve this problem?

**Comment by neomerx** [comment]
you can use `.env` file with `env()` function

**Comment by chimit** [comment]
Still have a strange problem on POST requests from Postman. I get 400 Bad request. Lumen logs are empty. If I disable this package, it starts working again. I don't have any idea what's the reason.

**Comment by chimit** [comment]
Hm... the problem is in Chrome version of Postman. Standalone Postman works perfect with this package.

**Comment by neomerx** [comment]
@Chimit Can you turn logging on for the package and post logs here?

**Comment by chimit** [comment]
```
[2016-03-22 09:37:53] lumen.DEBUG: CORS analysis for request started.  
[2016-03-22 09:37:53] lumen.INFO: Request origin is not allowed. Check config settings for Allowed Origins. {"origin":"[object] (Neomerx\\Cors\\Http\\ParsedUrl: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop)"} 
[2016-03-22 09:37:53] lumen.DEBUG: CORS analysis for request completed.  
```

**Comment by neomerx** [comment]
@Chimit you can allow all origins by setting [this](https://github.com/neomerx/cors-illuminate/blob/master/config/cors-illuminate.php#L32) to `true`
