### ISSUE TITLE
Configuration Question: KEY_CHECK_HOST_HEADER

### ISSUE THREAD

**Issue by righter** [neomerx/cors-illuminate#16]
Hello, just curious if the `KEY_CHECK_HOST_HEADER` should be included in the published cors-illuminate config file.

Without this key, I get an `exception 'ErrorException' with message 'Undefined offset: 9'`.

It took some time tracing through the package src before finding this config option. After I add this key to my config file, the ErrorException goes away and everything appears to be in working order.

I searched the closed issues and could not find any reference to `KEY_CHECK_HOST_HEADER`

Thanks!

**Comment by neomerx** [comment]
@righter Sorry I didn't get if there is any bug in the package :smile: 

My second thought is recently `Settings` class in [parent library](https://github.com/neomerx/cors-psr7) changed and now supports get/set for all settings as `array`. So [Settings](https://github.com/neomerx/cors-illuminate/blob/master/src/Settings/Settings.php) could be simplified to a few lines of even removed in favor of its parent. Though the parent has some keys incompatible (my bad I should've paid more attention to that) so the package should be released as v2.0.0

Back to may initial question. If there is a bug in the current version I'll fix it, release v1.1.2, refactor `Settings` and publish v2.0.0.

**Comment by neomerx** [comment]
@righter Refactoring is ready to be merged in [this branch](https://github.com/neomerx/cors-illuminate/tree/feature/issue16). Let me know if there is a bug in current version so I can move on.

**Comment by righter** [comment]
@neomerx -- Thanks for the reply.

After running artisan publish, I had to add two keys to the generate config/cors-illuminate.php file:

``` php
    /**
     * If allowed methods should be added to pre-flight response when 'simple' method is requested.
     */
    S::KEY_FORCE_ADD_METHODS => false,

    /**
     * If request 'Host' header should be checked against server's origin.
     */
    S::KEY_CHECK_HOST_HEADER => false,
```

Without these keys in the config file, an exception was being thrown about missing array key indexes. I would consider this a bug in the current version.
