### ISSUE TITLE
OPTIONS request fails without Accept header

### ISSUE THREAD

**Issue by mphasize** [neomerx/cors-illuminate#20]
It looks like the OPTIONS request prior to the backend request fails with `400: Bad Request` when no Accept header is present in the OPTIONS request.

This is a problem, because the `Accept` header included with OPTIONS doesn't seem to be standardized and cannot be modified by JavaScript.
- Chrome sends `Accept: */*`
- Firefox sends: `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`
- Safari **does not send Accept** - instead it asks, if it would be okay to send Accept: `Access-Control-Request-Headers    accept, origin, authorization`

Since the spec ( https://www.w3.org/TR/cors/ ) doesn't mention Accept header in OPTIONS request, I think it would be best to ignore the Accept header.

**Comment by neomerx** [comment]
issue specific to correct app settings
mac requires additional header 'origin' if added to config it solves the problem

**Comment by mphasize** [comment]
Thanks for solving and sorry for the confusion!
