### ISSUE TITLE
When i do get Request it works but when i do Post Request it gives error

### ISSUE THREAD

**Issue by khanakia** [neomerx/cors-illuminate#21]
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://domain1.react.pma' is therefore not allowed access. The response had HTTP status code 400.

**Comment by neomerx** [comment]
CORS configuration could be found here https://github.com/neomerx/limoncello-collins/blob/master/config/cors-illuminate.php

**Comment by khanakia** [comment]
Yes i know configuration file i configured correctly. It gives that error when i made OPTIONS request and it gives that error

**Comment by neomerx** [comment]
@mrkhanakia CORS [can write detailed logs](https://github.com/neomerx/limoncello-collins/blob/master/config/cors-illuminate.php#L10) which typically help to resolve issues. Can you please post here logs for the request you have problems with?

**Comment by neomerx** [comment]
No feedback

**Comment by iamface** [comment]
I had this same issue. Enabling the logs showed
`Check config settings for Allowed Headers. {"header":"content-type"}`
`Check config settings for Allowed Headers. {"header":"authorization"} `

I updated the config to the following and the `POST` requests would work.
`
S::KEY_ALLOWED_HEADERS => [
        'content-type' => true,
        'authorization' => true,
]
`

**Comment by neomerx** [comment]
@iamface Thanks for feedback
