### ISSUE TITLE
Android?

### ISSUE THREAD

**Issue by hopewise** [neomerx/cors-illuminate#22]
As I am trying to access my API server from Android, I started to get errors:

```
[2016-08-24 09:44:06] lumen.DEBUG: CORS analysis for request started.  
[2016-08-24 09:44:06] lumen.DEBUG: Request is not CORS (request origin is empty or equals to server one). Check config settings for Server Origin. {"request":null,"server":"[object] (Neomerx\\Cors\\Http\\ParsedUrl: http://192.168.1.34:9907)"} 
[2016-08-24 09:44:06] lumen.DEBUG: CORS analysis for request completed.  
```

Although I set this in my settings:

```
S::KEY_ALLOWED_ORIGINS => [S::VALUE_ALLOW_ORIGIN_ALL => true],
```

But I keep getting the same error, please advice.

**Comment by neomerx** [comment]
I think server `Origin` is fine. You have a problem with `Origin` header in request (it absent).

According to the [specification 6.2.1](https://www.w3.org/TR/cors/#resource-preflight-requests) (and 6.1.1 as well) if no `Origin` header is present in request it's not a CORS. And that's exactly what the lib does.

**Comment by hopewise** [comment]
But, what would be the value for the `Origin` header in request?

**Comment by neomerx** [comment]
Browser puts an origin of where the javascript was taken from. For example if executed script was received from 'www.yourdomain.com/js/code.js' it will be 'www.yourdomain.com'. So server can decide if it handles requests from other sites. Or course with tools like `curl` it could be easily bypassed but with browsers this security feature works this way.

**Comment by hopewise** [comment]
In my Android app, I am not using a browser, its a native code that calls Rest APIs, is there any recommended `Origin` value in such case?

**Comment by neomerx** [comment]
The same value you use in config for `origin` should be fine.
