### ISSUE TITLE
User error details needed

### ISSUE THREAD

**Issue by asamuga** [neomerx/cors-illuminate#23]
I added this package but my problem wasnt solved!

**Comment by neomerx** [comment]
Will you provide any details?

**Comment by asamuga** [comment]
I installed it for Lumen, set true so that ever origin can access and nothing. It doesnt work

**Comment by neomerx** [comment]
Lumen version?

**Comment by neomerx** [comment]
Also plz turn on logging in settings and post it with Lumen version number.

**Comment by neomerx** [comment]
And, sorry, one more question: how do you check it doesn't work?

**Comment by neomerx** [comment]
A side note. Some users install the CORS package then do same-origin request (the CORS package does what it should do in such a case - do nothing and exit as early as possible) and then claim it doesn't work.
You need to make/emulate Cross-Origin request to see any effect.

**Comment by asamuga** [comment]
Lumen version is 5.2.9. I have a domain mydomain.com and subdomain api.mydomain.com. Lumen is on api.mydomain.com. 

I make angular http request from mydomain.com to api.mydomain.com and in browser's console I get an error

`XMLHttpRequest cannot load http://api.mydomain.com/jump/?id=28558. Redirect from 'http://api.mydomain.com/jump/?id=28558' to 'http://api.mydomain.com/jump?id=28558' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mydomain.com' is therefore not allowed access`

**Comment by neomerx** [comment]
Can you please turn on CORS logs (will be written to the same file as lumen logs) and post it? The package writes detailed logs so it might give some hints what kind of problem (most likely in configuration) you have.

**Comment by neomerx** [comment]
Just to remind. The actual CORS request consists of 2 actual HTTP requests. The first one browser sends to server and basically asking 'I have a script which wants to make a request with the following params. Can you reply what is allowed?' This request is handled by CORS middleware and what will be sent back depends on settings.

**Comment by asamuga** [comment]
I turned on logging for CORS but nothing gets written in lumen.log

btw. when I make a request to lumen I get status 301 moved permanently.

This is response:

```
HTTP/1.1 301 Moved Permanently
Date: Mon, 10 Oct 2016 14:56:32 GMT
Content-Type: text/html; charset=iso-8859-1
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=d79b583e1456a625f536e7c26bb7051541476111392; expires=Tue, 10-Oct-17 14:56:32 GMT; path=/; domain=.mydomain.com; HttpOnly
Location: http://api.mydomain.com/jump?id=28558
Age: 0
X-Cache: MISS
Server: cloudflare-nginx
CF-RAY: 2efaeb6bf2745-VIE
```

**Comment by neomerx** [comment]
Tried on new lumen (just as in installation instruction)

``` bash
composer create-project --prefer-dist laravel/lumen blog
cd blog
./vendor/bin/phpunit
composer require neomerx/cors-illuminate
```

in `bootstrap/app.php` add CORS middleware

``` php
$app->middleware([
    \Neomerx\CorsIlluminate\CorsMiddleware::class, // <-- this line
]);

...

// ... and this one as well
$app->register(\Neomerx\CorsIlluminate\Providers\LumenServiceProvider::class);
```

copy config file

``` bash
mkdir config && cp ./vendor/neomerx/cors-illuminate/config/cors-illuminate.php ./config/cors-illuminate.php
```

enable CORS logging in `./config/cors-illuminate.php`

``` php
    S::KEY_LOGS_ENABLED  => true,
```

run test

``` bash
./vendor/bin/phpunit
```

in `./storage/logs/lumen.log`

```
[2016-10-11 11:03:08] lumen.DEBUG: CORS analysis for request started.  
[2016-10-11 11:03:08] lumen.DEBUG: Request is not CORS (request origin is empty or equals to server one). Check config settings for Server Origin. {"request":null,"server":"[object] (Neomerx\\Cors\\Http\\ParsedUrl: http://localhost:8080)"} 
[2016-10-11 11:03:08] lumen.DEBUG: CORS analysis for request completed.  
```

Yes CORS in not configured and the request wasn't CORS but it does writes logs. Can you please check you haven't missed anything?

**Comment by asamuga** [comment]
I gave up on this plugin and went with this since it works.

https://gist.github.com/ardani/168015be6e0f789f0e09efc10ce54810

**Comment by neomerx** [comment]
Ugly but should work
