### ISSUE TITLE
Global middleware breaking passport route in chrome and safari

### ISSUE THREAD

**Issue by deadlysyntax** [neomerx/cors-illuminate#24]
Hi, placing the middleware globally is causing issues with requests related to web routes, specifically the built-in Passport web route **POST /password/email**, it's returning a 400 error in chrome and safari (but not firefox). If I remove the middleware from my global middleware list this route starts working again for chrome/safari, but obviously breaks cors for the rest of my api-specific requests. Is there any way around this?

**Comment by neomerx** [comment]
Hi, it means FF and chrome send different requests and you configured CORS in a way it allows requests from FF but not from chrome. Can you enable logging in your [configuration](https://github.com/neomerx/cors-illuminate#3-configuration)? It might give an idea for the fix.

**Comment by deadlysyntax** [comment]
Thanks, this is the only potential info gleaned from the logging data and it doesn't mean much to me: 

`Request is not CORS (request origin is empty or equals to server one). Check config settings for Server Origin. {"request":null,"server":"[object] (Neomerx\\Cors\\Http\\ParsedUrl: https://mydomain.com)"}`

We had a pretty hard look at the requests and didn't see any differences. Are there any particular headers that would be worth checking again, perhaps something usually different between chrome and firefox? I see nothing in the config that looks like it would cause distinct issues between FF and Chrome.

**Comment by deadlysyntax** [comment]
Fixed it. Config was incorrect. Appreciate you help.

**Comment by neomerx** [comment]
@deadlysyntax Could you please post what was the difference? Just for history if anyone has a similar issue.
