### ISSUE TITLE
Add config option for logging errors

### ISSUE THREAD

**Issue by neomerx** [neomerx/cors-illuminate#8]
Most frequent is `origin` not configured which causes 400 error which is very hard to track down.
It should be logged if logging is on in settings.

**Comment by neomerx** [comment]
After thinking a while... Because of dependencies it will be better to extend middleware and add logging in projects that use this package.

**Comment by LavaToaster** [comment]
@neomerx How is this done? It is _very_ _**very**_ hard to debug missing headers when there is nothing provided by this package. Colleagues of mine have spent a day trying to debug a missing "Authorisation" header in the config because there was nothing to go by.

**Comment by neomerx** [comment]
@Lavoaster Maybe add logging + config option to turn it on/off? Where do you think logs are needed?

**Comment by LavaToaster** [comment]
I think they're most needed when the cors package determines a request should be denied.

**Comment by neomerx** [comment]
@Lavoaster a new config key was added to `config/cors-illuminate.php`. If enabled it should output detailed logs to standard Laravel log.

``` php
    ...
    /**
     * If CORS handling should be logged. Debugging feature.
     */
    Settings::KEY_LOGS_ENABLED  => false,
    ...
```

**Comment by LavaToaster** [comment]
@neomerx :heart: Thanks.

**Comment by neomerx** [comment]
sample output for not allowed origin (request via postman)

```
[2016-03-10 23:08:11] local.DEBUG: CORS analysis for request started.  
[2016-03-10 23:08:11] local.INFO: Request origin is not allowed. {"origin":"chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop"} 
[2016-03-10 23:08:11] local.DEBUG: CORS analysis for request completed.  
```
