### ISSUE TITLE
Configure allowed origins

### ISSUE THREAD

**Issue by psopacua** [neomerx/cors-illuminate#9]
If a preflight "options"  requests is done it still give's me "Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

what am i doing wrong i just cant figure it out... even added "options"  to Settings::key_ALLOWED_METHODS didnt fix it

**Comment by neomerx** [comment]
Can you please give a list of all headers you send?

**Comment by neomerx** [comment]
After re-reading the question. By default localhost:80 is allowed. Most likely you use other port. You can change [allowed origins](https://github.com/neomerx/cors-illuminate/blob/master/config/cors-illuminate.php#L23-L26) to 'all allowed'

``` php
    Settings::KEY_ALLOWED_ORIGINS => [
        '*' => true,
    ],
```

**Comment by neomerx** [comment]
let me know if the issue should be re-opened

**Comment by psopacua** [comment]
Hi,

Nevermind! i haved fixed the problem!
Because of PHP5.6 deprecated warning about HTTP_RAW_POST_DATA  & used $request->input to get the data the error came!

Thanx anyway!

Kindly regards,

psopacua

**Comment by neomerx** [comment]
btw Laravel 5.2 came out and I've upgraded the library. The latest version become stable (v1.0)
